name: react-ln CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master, develop ]
jobs:
  pipeline-ci:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        node-version: [ 16.x ]

    runs-on: ${{ matrix.os }}

    steps:
#      - uses: actions/chekout@v2
      - name: Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm ci

      - name: production build
        run: npm run build:prod

      - name: lint typescript
        run: npm run lint:ts

      - name: lint scss
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit
